azureDevOps:
  organization: "krateo-kog"

teamProject:
  verbose: true
  name: "project-from-composition"
  description: "Created by Krateo Composition"
  visibility: private
  capabilities:
    versioncontrol:
      sourceControlType: "Git"
    processTemplate:
      templateTypeId: "6b724908-ef14-45cf-84f8-768b5384da45"

environment:
  verbose: true
  name: "environment-from-composition"
  description: "Created by Krateo Composition"
