apiVersion: composition.krateo.io/v0-0-10
kind: AzuredevopsStarter
metadata:
  labels:
    krateo.io/composition-version: v0-0-10
  name: azuredevops-starter
  namespace: demo-system
spec:
  azureDevOps:
    organization: "krateo-kog"
    version: v25.0.0
    version2: 250
    version3:
      key1: "value1"
      key2: "value2"
  
  teamProject:
    verbose: true
    name: "project-from-composition"
    #description: "Created by Krateo Composition"

  environment:
    verbose: true
    name: "environment-from-composition"
    description: "Created by Krateo Composition"
