apiVersion: azuredevops.krateo.io/v1alpha1
kind: TeamProject
metadata:
  name: {{ .Values.teamProject.name | lower }}
  namespace: demo-system
  annotations:
    krateo.io/connector-verbose: "{{ .Values.teamProject.verbose }}"
spec:
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample

  organization: {{ .Values.azureDevOps.organization }}
  name: {{ .Values.teamProject.name }}
  description: {{ .Values.teamProject.description }}
  
  visibility: {{ .Values.teamProject.visibility | default "private" }}
  capabilities:
    versioncontrol:
      sourceControlType: {{ .Values.teamProject.capabilities.versioncontrol.sourceControlType | default "Git" }}
    processTemplate:
      templateTypeId: {{ .Values.teamProject.capabilities.processTemplate.templateTypeId | default "6b724908-ef14-45cf-84f8-768b5384da45" }}
