apiVersion: azuredevops.krateo.io/v1alpha1
kind: Environment
metadata:
  name: {{ .Values.environment.name | lower }}
  namespace: demo-system
  annotations:
    krateo.io/connector-verbose: "{{ .Values.environment.verbose }}"
spec:
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample

  projectRef:
    name: {{ .Values.teamProject.name | lower }}
    namespace: "default" # teamproject resource is not namespaced
  name: {{ .Values.environment.name }}
  description: {{ .Values.environment.description | default "Created by Krateo Composition" }}
